#!/bin/bash
# OpenSpec 自动修复脚本
# 运行: bash scripts/auto-fix.sh

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "========================================"
echo "  OpenSpec 自动修复引擎"
echo "========================================"
echo ""

FIXED_COUNT=0

# ========== 修复1: Import路径错误 ==========
echo "[修复1] 检测并修复 import 路径错误..."

find client/src/components/ -name "*.tsx" -o -name "*.ts" | while read file; do
    if grep -q "from '\.\.\/components\/ui\/Icons'" "$file" 2>/dev/null; then
        echo "  修复: $file"
        # macOS sed
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/from '\.\.\/components\/ui\/Icons'/from '..\/ui\/Icons'/g" "$file"
        else
            sed -i "s/from '\.\.\/components\/ui\/Icons'/from '..\/ui\/Icons'/g" "$file"
        fi
        FIXED_COUNT=$((FIXED_COUNT + 1))
    fi
done

echo "  完成！修复 $FIXED_COUNT 处 import 路径错误"
echo ""

# ========== 修复2: 创建缺失目录 ==========
echo "[修复2] 创建缺失目录..."

declare -a DIRS=(
    "data/uploads"
    "data/chroma"
    "data/exports"
    "client/src/pages/Home"
    "client/src/pages/LearningSpace"
    "client/src/pages/QuizCenter"
    "client/src/pages/QuizPlay"
    "client/src/pages/QuizReport"
    "client/src/pages/Profile"
    "client/src/components/ui"
    "client/src/components/business"
    "client/src/components/layout"
    "client/src/stores"
    "client/src/api"
    "client/src/hooks"
    "client/src/utils"
    "backend/routers"
    "backend/services"
    "electron"
    "scripts"
)

for dir in "${DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        echo "  创建目录: $dir"
        FIXED_COUNT=$((FIXED_COUNT + 1))
    fi
done

echo "  完成！"
echo ""

# ========== 修复3: 创建空的 __init__.py ==========
echo "[修复3] 创建 Python 包初始化文件..."

declare -a INIT_FILES=(
    "backend/routers/__init__.py"
    "backend/services/__init__.py"
)

for file in "${INIT_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo "# Auto-generated by OpenSpec auto-fix" > "$file"
        echo "  创建: $file"
        FIXED_COUNT=$((FIXED_COUNT + 1))
    fi
done

echo "  完成！"
echo ""

# ========== 修复4: 初始化数据库 ==========
echo "[修复4] 初始化数据库..."

if [ -f "backend/database.py" ]; then
    cd backend
    python3 -c "from database import init_db; init_db()" 2>/dev/null
    if [ $? -eq 0 ]; then
        echo "  数据库初始化成功"
    else
        echo "  数据库初始化失败（可能Python环境未就绪）"
    fi
    cd ..
fi

echo ""

# ========== 修复5: 设置脚本执行权限 ==========
echo "[修复5] 设置脚本执行权限..."

chmod +x start.sh 2>/dev/null
chmod +x install.sh 2>/dev/null
chmod +x scripts/*.sh 2>/dev/null

echo "  完成！"
echo ""

# ========== 修复6: 依赖安装检查 ==========
echo "[修复6] 依赖安装检查..."

if [ -f "client/package.json" ]; then
    cd client
    if [ ! -d "node_modules" ]; then
        echo "  前端依赖未安装，执行 npm install..."
        npm install 2>/dev/null
        if [ $? -eq 0 ]; then
            echo "  前端依赖安装成功"
            FIXED_COUNT=$((FIXED_COUNT + 1))
        else
            echo "  前端依赖安装失败"
        fi
    fi
    cd ..
fi

if [ -f "backend/requirements.txt" ]; then
    if ! python3 -c "import fastapi" 2>/dev/null; then
        echo "  后端依赖未安装，执行 pip3 install..."
        pip3 install -r backend/requirements.txt 2>/dev/null
        if [ $? -eq 0 ]; then
            echo "  后端依赖安装成功"
            FIXED_COUNT=$((FIXED_COUNT + 1))
        else
            echo "  后端依赖安装失败"
        fi
    fi
fi

echo ""

# ========== 修复7: .env.example 生成 ==========
echo "[修复7] 检查 .env.example..."

if [ ! -f "backend/.env.example" ] && [ -f "backend/.env" ]; then
    cp backend/.env backend/.env.example
    echo "  从 .env 生成 .env.example"
    FIXED_COUNT=$((FIXED_COUNT + 1))
fi

if [ ! -f "client/.env.example" ] && [ -f "client/.env" ]; then
    cp client/.env client/.env.example
    echo "  从 .env 生成 .env.example"
    FIXED_COUNT=$((FIXED_COUNT + 1))
fi

echo ""

echo "========================================"
echo "  自动修复完成！"
echo "  修复项数: $FIXED_COUNT"
echo "  请重新运行 check-completeness.sh 验证"
echo "========================================"